---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-app
spec:
  selector:
    app: {{ .Chart.Name }}-{{ .Release.Name }}-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8888
