---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-nginx
spec:
  selector:
    app: {{ .Chart.Name }}-{{ .Release.Name }}-nginx
  ports:
  - protocol: TCP
    port: 80
  type: NodePort
